### ISSUE TITLE
Magisk v20.3+ Version

### ISSUE THREAD

**Issue by ajayyy** [ammmze/magisk-recovery#2]
I made an updated build for Magisk v20.3. This one is based on commit fbe776db0bdfcbf3b1052381ca43382a61175aa5 and is slightly ahead of v20.3.

To use this version, set your update channel to: `https://raw.githubusercontent.com/ajayyy/magisk-recovery/magisk-latest-jan27/custom.json`

**Comment by ammmze** [comment]
👍 thank you ... i've merged #1 to pull that in
